import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "./ui/root-layout/Navbar";

const urbanist = localFont({
  src: "./fonts/urbanist/Urbanist-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
